#!/usr/bin/env bash

# **********************************
# *                                *
# *  erase and write image copy    *
# *                                *
#***********************************
#


_main_code () {

	while [[ $REPLY != 'x' ]]; do
		clear && echo ''
  	cat <<_EOF_
  erase and write image copyrights:

    1. do one file

    2. do a bunch of files

    x. eXit

_EOF_

  read -p "Enter selection [ExIT or 1] > "
  if [[ $REPLY =~ ^[1-2]$ || $REPLY =~ ^[?]$  || $REPLY =~ ^[x]$ ]]; then

  	if [[ $REPLY == 'x' ]]; then
  		echo ''
      echo '  eXit Convert Routine! By by ...'
      echo ''
  	fi


    if [[ $REPLY == 1 ]]; then

      ORIGINIMGPATH="${HOME}/Pictures/ZZ-images/AA-destination"
      DESTINIMGPATH="${HOME}/Pictures/ZZ-images/AA-destination"

      read -p 'Insert file name ... :'
      echo ''
      if [[ "${REPLY}" != "" && -f "${ORIGINIMGPATH}/${REPLY}" ]]; then

        # erase all image metadata
        #mogrify \
        #  -strip \
         # ${ORIGINIMGPATH}/${REPLY}
        exiftool -All:All= \
          -TagsFromFile ${ORIGINIMGPATH}/${REPLY} \
          -Make -Model \
          -ExposureTime \
          -FNumber \
          -ISO \
          -FocalLength \
          -LensModel \
          ${ORIGINIMGPATH}/${REPLY}

        read -p "${REPLY} Metadata erased ... : press any key to continue!"

        # write copyrights data
        exiftool \
          -Artist="roTokyo" \
          -ArtistCity="Tokyo" \
          -ArtistCountry="Japan" \
          -ArtistWorkURL="https://rotokyo.github.io" \
          -ArtistWorkEmail="rotokyo@icloud.com" \
          -CopyRightsOwner="Roberto Calesini" \
          -UsageTerms="--CC BY-NC-SA 4.0--" \
          -UsageWebStatement="https://creativecommons.org/licenses/by-nc-sa/4.0/" \
          ${ORIGINIMGPATH}/${REPLY}
        exiftool -a -G1 -s -H ${ORIGINIMGPATH}/${REPLY}
        read -p "${REPLY} New metadata saved ... : press any key to continue!"
			else
		    	echo ''
		      echo '  Invalid entry! Wait ...'
		      echo ''
		      sleep 1

      fi
  	fi

  	if [[ $REPLY == 2 ]]; then
  	  ORIGINIMGPATH="${HOME}/Pictures/ZZ-images/AA-destination"

  	  for file in $ORIGINIMGPATH/*.jpg; do
  	    if [[ -f ${file} ]]; then
          exiftool -All:All= \
            -TagsFromFile ${file} \
            -Make -Model \
            -ExposureTime \
            -FNumber \
            -ISO \
            -FocalLength \
            -LensModel \
            ${file}

          exiftool \
						-Artist="roTokyo" \
						-ArtistCity="Tokyo" \
						-ArtistCountry="Japan" \
						-ArtistWorkURL="https://rotokyo.github.io" \
						-ArtistWorkEmail="rotokyo@icloud.com" \
						-CopyRightsOwner="Roberto Calesini" \
						-UsageTerms="--CC BY-NC-SA 4.0--" \
						-UsageWebStatement="https://creativecommons.org/licenses/by-nc-sa/4.0/" \
            ${file}
          echo "File: ${file} modified! ... "
        else
		    	echo ''
		      echo '  No *.jpg files found!'
		      echo ''
          read -p "Press any button to continue ... :"
	      fi
      done

  	fi
  fi
	done
  unset DESTINIMGPATH ORIGINIMGPATH REPLY
}

_main_code
