#!/usr/bin/env bash

# **********************************
# *                                *
# *    Write draft for roTokyo     *
# *                                *
#***********************************
#

readonly DESTINATION="$HOME/Projects/roTokyo/source/_drafts/"

function _write () {
  unset REPLY
	seek_confirmation "Insert draft name:"
	if is_confirmed
		then
echo "---
published:   false
title:
description:
image:
figCaption:  - © roTokyo
itinerario:
quando:
giorno:
indirizzo:
tags:

youTubeId:

location:
  - title:
    latitude:
    longitude:
    zoom:
    markerimage:

seo:
  description:

sitemap:
  lastmod: 

date:

---
{% capture imgpath %}{{site.baseurl}}{{site.imageurlpost}}{%endcapture%}

" > $DESTINATION$REPLY
			read -p "$(_f_alert_success 'Press any button to EXIT ⧳ ')" -n 1
	  else
	  	_f_alert_warning "Enter a valid file name!"
		fi
}


function seek_confirmation() {
  #input "$@"
  read -p "$(_f_alert_input "$@")" -n 1
  echo ""
}

function is_confirmed() {
  if [[ "${REPLY}" =~ ^[Yy]$ ]]; then
    return 0
  fi
  return 1
}

_alert() {

  ORANGE=$(tput setaf 166)
	RED=$(tput setaf 1)
	RESET=$(tput sgr0)
	TAN=$(tput setaf 3)

	if [[ "${1}" = "info" || "${1}" = "notice" ]];    then local COLOR=""; fi
	if [[ "${1}" = "input" ]];   then local COLOR="${RED}"; fi
	if [[ "${1}" = "success" ]]; then local COLOR="${TAN}"; fi
	if [[ "${1}" = "warning" ]]; then local COLOR="${RED}"; fi
	if [[ "${1}" = "menu" ]];    then local COLOR="${ORANGE}"; fi

	echo -e "${COLOR}$(printf "[%9s]" "${1}") ${MESSAGE}${RESET}"
}

_f_alert_info ()      { local MESSAGE="${*}"; echo "$(_alert info)"; }
_f_alert_input ()     { local MESSAGE="${*}"; echo "$(_alert input)"; }
_f_alert_notice ()    { local MESSAGE="${*}"; echo "$(_alert notice)"; }
_f_alert_menu()       { local MESSAGE="${*}"; echo "$(_alert menu)"; }
_f_alert_success ()   { local MESSAGE="${*}"; echo "$(_alert success)"; }
_f_alert_warning ()   { local MESSAGE="${*}"; echo "$(_alert warning)"; }

_byby() {
  cat <<_EOF_

[     exit]

_EOF_
	read -p "$(_f_alert_input 'Press any button to EXIT ⧳ ')" -n 1
	unset ORIGIN DESTINATION
	clear
	exit
}

_write
_byby
