#!/usr/bin/env bash

# **********************************
# *                                *
# *    Write draft for roTokyo     *
# *                                *
#***********************************
#

readonly WEBSITENAME="roTokyo"
readonly DESTINATION="$HOME/Desktop/"
readonly DRAFT__DATE="$(date "+%Y-%m-%d")"
readonly    FILE_EXT=".md"
readonly       DELAY="2"

function _write () {


echo "---
published:   false
title:       ''      #Important for SEO
description: ''      #Important for SEO
keywords:    ''      #Important for SEO
author:      ''

figure:
  image:     .jpg
  caption:   ' - © roTokyo'
  facebook:  -fb.jpg   # Important ratio of 1.9:1      (1200 x 630 o 1200 x 1200 sono perfette)
  twitter:   -tw.jpg   # non serve usa in automatico facebook image ma ratio of 2:1 o 1:1 (1200 x 1200 sono perfette)

#image:
#figCaption: - © roTokyo
itinerario:
quando:
giorno:
indirizzo:

tags:        ['tag1', 'tag2']
categories:  ['category1', 'category2']
#permalink:

youTubeId:

location:
  - title:
    latitude:
    longitude:
    zoom:
    markerimage:

sitemap:
  lastmod:
  changefreq:
  priority:
  exclude:     #per ecludere: Yes
---


#### {{page.description}}
{: .sottotitolo}

### ITINERARIO
{{page.quando}}
{: .quando}
Itinerario: {{page.itinerario}}
{: .itinerario}
{: style=\"margin-bottom: 2em;\"}


### RACCONTO e MOSTRE
{{page.itinerario}}
{: .itinerario}
{{page.giorno}}
{: .itinerario}
{: style=\"margin-bottom: 2em;\"}


### TEMPIO e MOSTRE
{{page.quando}}
{: .quando}
> {{page.indirizzo}}
{: style=\"margin-bottom: 2em;\"}

" > ${DESTINATION}${DRAFT__DATE}"-"${REPLY}${FILE_EXT}
}

echo ' '
echo " Create a draft for ${WEBSITENAME}"
read -p ' Enter file name (no extention) > '
if [[ $REPLY ]]; then
  DRAFT_NAME="$REPLY"
  if [[ -f ${DESTINATION}${DRAFT__DATE}"-"${DRAFT_NAME}${FILE_EXT} ]]; then
    echo ' '
    echo ' No, no, no! File already exist!'
    echo ' Try again ... !'
    echo ' '
    else
      echo ' Creating file ...'
      _write
      cd $DESTINATION
      sleep $DELAY
      echo ' '
      read -p  " Do you want to open ${DRAFT_NAME}.md with ATOM? [yY]" -n 1
      if [[ $REPLY =~ ^[Yy]$ ]]; then
        atom "${DESTINATION}${DRAFT__DATE}-${DRAFT_NAME}${FILE_EXT}"; echo ''
        echo ' '
        fi
      echo ' '
      echo ' Thank you ... enjoy!'
    fi
  else
    echo ' '
    echo ' Name pleeeese!'
    echo ' Do it again ... '
    echo ' '
    echo ' By ... by ... '
    echo ' '
    sleep $DELAY
  fi














