#!/usr/bin/env bash

# **********************************
# *                                *
# *    Write draft for roTokyo     *
# *                                *
#***********************************
#

readonly WEBSITENAME="roTokyo"
readonly DESTINATION="$HOME/Projects/roTokyo/source/_drafts/"
readonly DRAFT__DATE=`date "+%Y-%m-%d"`
readonly DRAFT__NAME="test"
readonly    FILE_EXT=".md"
readonly       DELAY="2"

function _write () {


echo "---
published:   false
title:
description:
image:
figCaption:  - © roTokyo
itinerario:
quando:
giorno:
indirizzo:
tags:

youTubeId:

location:
  - title:
    latitude:
    longitude:
    zoom:
    markerimage:

seo:
  description:

sitemap:
  lastmod: ${DRAFT__DATE}

date: ${DRAFT__DATE}

---
{% capture imgpath %}{{site.baseurl}}{{site.imageurlpost}}{%endcapture%}

" > ${DESTINATION}${DRAFT__DATE}"-"${DRAFT__NAME}${FILE_EXT}
}

echo " Create a draft for ${WEBSITENAME}"
read -p ' Enter file name (no extention) > '
if [[ $REPLY ]]; then
  if [[ -f ${DESTINATION}${DRAFT__DATE}"-"${DRAFT__NAME}${FILE_EXT} ]]; then
    echo ' No, no, no! File already exist!'
    echo ' Try again ... !'
    else
      _write
      cd $DESTINATION
      echo ' File created ...'
      sleep $DELAY
    fi
  else
    echo ' Name pleeeese!'
    echo ' Do it again ... '
    sleep $DELAY
  fi

echo ' By by ... '
