#!/usr/bin/env bash

echo "Il processo è irreversibile ... continuo?"
read -p "    [To exit press any key ... 1 to go] > "
if [[ $REPLY =~ ^[1] ]]; then
ORIGINIMGPATH="${HOME}/Pictures/ZZ-images/AA-destination"

  for file in $ORIGINIMGPATH/*.jpg; do

    if [[ -f ${file} ]]; then
    # NOTA:
    # Cancella tutto
      exiftool -All:All= ${file}


    # estrae nome file completo: echo $(basename "$(dirname "$file")") con spazi vuoti
    # estrae nome file completo: echo $(basename $file) ma non accetta spazi vuoti
    # Estrae nome file: echo "${file##*/}"
    # Estrae nome file: echo "${file%.*}"
    # Estrae estensione: echo "${file##*.}"
    # nomefiledacancellare="${file%.*}.jpg_original"
    echo "File elaborati: " $(basename $file)

    # NOTA:
    #
    # Cancella i file di sicurezza
    # Processo irreversibile
    # ATTENZIONE NON USARE SU ORIGINALI
    #
      if [[ -f ${file%.*}".jpg_original" ]]; then
        rm -f ${file%.*}".jpg_original"
        echo "Cancellato: " ${file%.*}".jpg_original"
      fi
    fi
  done
  read -p "Fine > "
else
  echo "Stop"
fi
