#!/usr/bin/env bash

echo "Il processo è irreversibile ... continuo?"
read -p "    [To exit press any key ... 1 to go] > "
if [[ $REPLY =~ ^[1] ]]; then
ORIGINIMGPATH="${HOME}/Pictures/ZZ-images/AA-destination"

  for file in $ORIGINIMGPATH/*.jpg; do

    if [[ -f ${file} ]]; then
    # NOTA:
    #
    # Scala il file 16x16 e SOVRASCRIVE
    # ATTENZIONE NON USARE SU ORIGINALI
    #
      mogrify \
        ${file} \
        -thumbnail 16x16 \
      	-filter Gaussian \
      	-blur 0x8 \
        ${file}
    fi
    echo "File elaborati: " $(basename $file)
  done
  read -p "Fine > "
else
  echo "Stop"
fi
