#!/usr/bin/env bash

echo "Il processo è irreversibile ... continuo?"
read -p "    [To exit press any key ... 1 to go] > "
if [[ $REPLY =~ ^[1] ]]; then
ORIGINIMGPATH="${HOME}/Pictures/ZZ-images/AA-destination"

  for file in $ORIGINIMGPATH/*.jpg; do
    # NOTA:
    #
    # Scala il file 420x420 e SOVRASCRIVE
    # ATTENZIONE NON USARE SU ORIGINALI
    #
    if [[ -f ${file} ]]; then
      mogrify \
        ${file} \
      	-scale 420 \
      	-quality 85 \
      	-define jpeg:fancy-upsampling=off \
        -unsharp 0.25x0.25+8+0.065 \
        -dither None \
        -interlace none \
        -colorspace sRGB \
        ${file}
      echo "File elaborati: " $(basename $file)
    else
      echo "Files non trovati"
    fi

  done

  read -p "Fine > "
else
  echo "Stop"
fi
